import os
from pathlib import Path
from dotenv import load_dotenv


BASE_DIR=Path(__file__).resolve().parent
load_dotenv(BASE_DIR/".env")

DATA_DIR=BASE_DIR/"data"
VIDEO_DIR=DATA_DIR/"videos"
AUDIO_DIR=DATA_DIR/"audio"
TRANSCRIPTS_DIR=DATA_DIR/"transcripts"
TRANSCRIPTS_CHUNK_DIR=DATA_DIR/"transcripts_chunks"
FRAMES_DIR=DATA_DIR/"frames"
CHROMA_DB_DIR=DATA_DIR/"chroma_db"
CHROMA_DB_EVAL_DIR=DATA_DIR/"chroma_db_eval"
TEXT_DB_PATH=CHROMA_DB_DIR/"text"
FRAME_DB_PATH=CHROMA_DB_DIR/"frames"
EVAL_TEXT_DB_PATH=CHROMA_DB_EVAL_DIR/"text"
EVAL_FRAME_DB_PATH=CHROMA_DB_EVAL_DIR/"frames"

EVALUATION_DIR=BASE_DIR/"evaluation_results"
QA_PAIRS_DIR=EVALUATION_DIR/"qa_pairs"
RETRIEVAL_EVAL_RESULTS_DIR=EVALUATION_DIR/"retrieval_eval_results"
JUDGE_EVAL_RESULTS_DIR=EVALUATION_DIR/"judge_eval_results"
RERANK_EVAL_RESULTS_DIR=EVALUATION_DIR/"rerank_eval_results"


OUTPUTS_DIR=BASE_DIR/"outputs"
LOG_DIR=OUTPUTS_DIR/"logs"
LOG_FILE=LOG_DIR/"app.log"

YOUTUBE_URL="YOUTUBE_URL"


DEVICE="cuda"
WHISPER_MODEL="base"
AUDIO_CHUNK_MINUTES=10

TEXT_CHUNK_THRESHOLD=1000
TEXT_EMBEDDING_MODEL="BAAI/bge-base-en-v1.5"
TEXT_RETRIEVER_K=20

CLIP_MODEL="clip-ViT-B-32"
FRAME_MIN_GAP_SEC=1.0
CLIP_SIMILARITY_THRESHOLD=0.95
FRAME_HISTORY_SIZE=20
FRAME_COLLECTION_NAME="frames"
FRAME_SCORE_THRESHOLD=15
FRAME_DETECTION_INTERVAL=5
FRAME_DETECTION_THRESHOLD_PERCENTILE=92



BM25_K=20
ENSEMBLE_WEIGHTS=[0.3, 0.7]
RERANKER_MODEL="BAAI/bge-reranker-base"
RERANK_K=5
CHAT_RERANK_K=3
FRAME_RESULTS_K=3
FRAME_RETRIEVER_N=FRAME_RESULTS_K
MAX_OCR_TOKEN=300
MAX_TURNS=3

TOTAL_QA_PAIRS=60

MAIN_LLM_MODEL="gemini-2.5-flash"
DECISION_LLM_MODEL="openai/gpt-oss-20b"
SUMMARY_LLM_MODEL="nvidia/nemotron-3-ultra-550b-a55b:free"
EVAL_LLM_MODEL="llama-3.3-70b-versatile"
JUDGE_LLM_MODEL="mistral-medium-3-5"

GEMINI_API_KEY=os.getenv("GEMINI_API_KEY")
GROQ_API_KEY=os.getenv("GROQ_API_KEY")
OPENROUTER_API_KEY=os.getenv("OPENROUTER_API_KEY")


LANGSMITH_TRACING=os.getenv("LANGSMITH_TRACING", "true")
LANGSMITH_ENDPOINT=os.getenv("LANGSMITH_ENDPOINT", "https://apac.api.smith.langchain.com")
LANGSMITH_PROJECT=os.getenv("LANGSMITH_PROJECT", "RAG_VideoAssistant")
LANGSMITH_API_KEY=os.getenv("LANGSMITH_API_KEY")

OPENAI_API_KEY=os.getenv("NARAROUTER_API_KEY")
OPENAI_BASE_URL=os.getenv("NARAROUTER_BASE_URL")


# VIDEO_ID="VIDEO_ID FOR EVALUATION"
VIDEO_ID="First_Law_of_Thermodynamics__Basic_Introduction_-_Internal_Energy__Heat_and_Work_-_Chemistry"
VIDEO_PATH= "PATH TO VIDEO FILE FOR CHAT"


VISION_DECISION_CACHE_TTL=60
CHAT_ANSWER_CACHE_TTL=120

JWT_SECRET_KEY=os.getenv("JWT_SECRET_KEY")
JWT_ALGORITHM="HS256"
JWT_EXPIRE_MINUTES=int(os.getenv("JWT_EXPIRE_MINUTES", "60"))
ANONYMOUS_OWNER_COOKIE=os.getenv("ANONYMOUS_OWNER_COOKIE", "anonymous_owner")
ANONYMOUS_OWNER_COOKIE_MAX_AGE=int(os.getenv("ANONYMOUS_OWNER_COOKIE_MAX_AGE", str(60 * 60 * 24 * 30)))
CORS_ORIGINS=[origin.strip() for origin in os.getenv("CORS_ORIGINS", "*").split(",") if origin.strip()]

REDIS_HOST=os.getenv("REDIS_HOST", "localhost")
REDIS_PORT=int(os.getenv("REDIS_PORT", "6379"))


DB_HOST=os.getenv("DB_HOST", "localhost")
DB_PORT=int(os.getenv("DB_PORT", "5432"))
DB_NAME=os.getenv("DB_NAME", "postgres")
DB_USER=os.getenv("DB_USER", "postgres")
DB_PASSWORD=os.getenv("DB_PASSWORD", "postgres")
DATABASE_URL=os.getenv("DATABASE_URL",f"postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}")


SESSION_ID="abc123"