CREATE TABLE IF NOT EXISTS videos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id VARCHAR(255) UNIQUE NOT NULL,
    title VARCHAR(500),
    youtube_url VARCHAR(1000),
    storage_path_url VARCHAR(2000),
    duration INTEGER,
    status VARCHAR(50) NOT NULL DEFAULT 'processing',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chat_sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(255) UNIQUE NOT NULL,
    video_id VARCHAR(255) NOT NULL,
    title VARCHAR(500),
    summary TEXT,
    summary_through_message_id INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_chat_sessions_video
        FOREIGN KEY (video_id)
        REFERENCES videos(video_id)
        ON DELETE CASCADE
);


CREATE INDEX IF NOT EXISTS idx_chat_sessions_video_id ON chat_sessions(video_id);


CREATE TABLE IF NOT EXISTS chat_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    role VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_chat_messages_session
        FOREIGN KEY (session_id)
        REFERENCES chat_sessions(session_id)
        ON DELETE CASCADE
);


CREATE INDEX IF NOT EXISTS idx_chat_messages_session_id ON chat_messages(session_id);